import { Box, Container } from "@mui/material";
import NextLink from "next/link";

import type {
  NextComponentType,
  NextLayoutComponentType,
  NextPageContext,
} from "next";
import Head from "next/head";
import { ReactNode } from "react";
import DashboardLayout from "../components/dashboardLayout";
import styles from "../styles/Home.module.css";

const Home: NextComponentType<NextPageContext, any, {}> &
  NextLayoutComponentType<{}> = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hotelian Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component="main"
        sx={{
          flexGrow: 1,
          py: 8,
          height: "100vh",
        }}
      >
        <Container maxWidth={false}>
          <h1 className={styles.title}>
            Welcome to <a href="https://hotelian.com">Hotelian </a>Admin Panel!
          </h1>

          <p className={styles.description}>
            <NextLink
              href="/login"
              passHref
              style={{ textDecoration: "underline" }}
            >
              click here for login
            </NextLink>
          </p>
        </Container>
      </Box>
    </div>
  );
};

Home.getLayout = (page: ReactNode) => <DashboardLayout>{page}</DashboardLayout>;
export default Home;
