import { Box, Container, FormControl, TextField } from "@mui/material";
import Head from "next/head";
import React, { ReactNode } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import DashboardLayout from "../components/dashboardLayout";
import { LoadingButton } from "@mui/lab";
import useLogin from "../apiCalls/useLogin";

const inputsStyles = {
  margin: ".4rem",
};

type LoginTypes = {
  userName: string;
  password: string;
};

const Login = () => {
  const { data, isLoading, error, fetchLoginData } = useLogin();

  const onSubmit: SubmitHandler<LoginTypes> = (values: LoginTypes) =>
    fetchLoginData(values);

  const { register, handleSubmit } = useForm<LoginTypes>({
    mode: "onChange",
    reValidateMode: "onChange",
  });

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          py: 8,
        }}
      >
        <Container
          maxWidth={false}
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          <h1>Login</h1>
          <FormControl>
            <TextField
              sx={inputsStyles}
              id="filled-basic"
              label="User Name"
              variant="filled"
              {...register("userName")}
            />
            <TextField
              {...register("password")}
              sx={inputsStyles}
              id="filled-basic"
              label="Password"
              variant="filled"
            />

            <LoadingButton
              loading={isLoading}
              sx={inputsStyles}
              variant="contained"
              onClick={handleSubmit(onSubmit)}
            >
              login
            </LoadingButton>
          </FormControl>
        </Container>
      </Box>
    </div>
  );
};

Login.getLayout = (page: ReactNode) => (
  <DashboardLayout>{page}</DashboardLayout>
);

export default Login;
