import { Box, Container, FormControl, TextField } from "@mui/material";
import Head from "next/head";
import React, { ReactNode } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import DashboardLayout from "../components/dashboardLayout";
import { LoadingButton } from "@mui/lab";
import useLogin from "../apiCalls/useLogin";
import { styled } from "@mui/material/styles";
import { getToken, setToken } from "../utils/getSetToken";
import { useRouter } from "next/router";

const LoginContainer = styled(Container)(({ theme }) => ({
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  background: theme.palette.primary.light,
  width: "fit-content",
  padding: "2rem",
  boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
  height: "100%",
}));
const inputsStyles = {
  margin: ".4rem",
};

type LoginTypes = {
  username: string;
  password: string;
};

const Login = () => {
  const { data, isLoading, error, fetchLoginData } = useLogin();
  const router = useRouter();

  React.useEffect(() => {
    if (data) {
      const token = data?.data?.result?.access_token;
      setToken(token);
      router.replace("/posts");
    }
  }, [data]);

  React.useEffect(() => {
    if (getToken()) {
      //we should verify the token first
      router.replace("/posts");
    }
  }, []);

  const onSubmit: SubmitHandler<LoginTypes> = (values: LoginTypes) =>
    fetchLoginData(values);

  const { register, handleSubmit } = useForm<LoginTypes>({
    mode: "onChange",
    reValidateMode: "onChange",
  });

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        sx={{
          flexGrow: 1,
          py: 8,
        }}
      >
        <LoginContainer maxWidth={false}>
          <h1>Login</h1>
          <FormControl>
            <TextField
              sx={inputsStyles}
              id="filled-basic"
              label="User Name"
              variant="filled"
              {...register("username")}
            />
            <TextField
              {...register("password")}
              sx={inputsStyles}
              id="filled-basic"
              label="Password"
              variant="filled"
            />

            <LoadingButton
              loading={isLoading}
              sx={inputsStyles}
              variant="contained"
              onClick={handleSubmit(onSubmit)}
            >
              login
            </LoadingButton>
          </FormControl>
        </LoginContainer>
      </Box>
    </div>
  );
};

Login.getLayout = (page: ReactNode) => (
  <DashboardLayout>{page}</DashboardLayout>
);

export default Login;
